import '@/components/Marquee/Marquee.makeswift'
import '@/components/accordion/accordion.makeswift'
import '@/components/button/button.makeswift'
import '@/components/carousel/carousel.makeswift'
import '@/components/component-styles/register'
import '@/components/navigation/navigation.makeswift'
import '@/components/tabs/tabs.makeswift'
